import type { AcceptanceDocument, AcceptanceScenario, AcceptanceStep } from '../model';

export interface PlaywrightAcceptanceGeneratorOptions {
  stepsImportPath: string;
}

export function generatePlaywrightAcceptanceSpec(
  documents: AcceptanceDocument[],
  options: PlaywrightAcceptanceGeneratorOptions
): string {
  const sections = documents.flatMap((document) => generateDocumentSections(document));

  return [
    '/* Generated by quality-tools acceptance compile. Do not edit. */',
    "import { test } from '@playwright/test';",
    `import { acceptanceSteps, createAcceptanceContext } from ${quote(options.stepsImportPath)};`,
    '',
    'type AcceptanceContext = Awaited<ReturnType<typeof createAcceptanceContext>> & { cleanup?: () => unknown | Promise<unknown> };',
    'type AcceptanceRuntimeStep = { keyword: string; text: string; sourcePath: string; line: number };',
    'type AcceptanceStepImplementation = (context: AcceptanceContext, step: AcceptanceRuntimeStep) => unknown | Promise<unknown>;',
    'type AcceptanceStepRegistry = Record<string, AcceptanceStepImplementation>;',
    '',
    'async function runAcceptanceStep(',
    '  context: AcceptanceContext,',
    '  stepText: string,',
    '  step: AcceptanceRuntimeStep',
    '): Promise<void> {',
    '  const registry = acceptanceSteps as AcceptanceStepRegistry;',
    '  const implementation = registry[stepText] ?? registry[`${step.keyword} ${stepText}`];',
    '',
    '  if (!implementation) {',
    '    throw new Error(`Missing acceptance step "${step.keyword} ${step.text}" at ${step.sourcePath}:${step.line}`);',
    '  }',
    '',
    '  await implementation(context, step);',
    '}',
    '',
    ...sections,
    ''
  ].join('\n');
}

function generateDocumentSections(document: AcceptanceDocument): string[] {
  const scenarios = document.scenarios.flatMap((scenario) => generateScenario(document.sourcePath, scenario));

  return [
    `test.describe(${quote(document.feature.name)}, () => {`,
    ...indentLines(scenarios, 2),
    '});',
    ''
  ];
}

function generateScenario(sourcePath: string, scenario: AcceptanceScenario): string[] {
  const steps = indentLines(scenario.steps.flatMap((step) => generateStep(sourcePath, step)), 2);

  return [
    `test(${quote(scenario.name)}, async ({}, testInfo) => {`,
    '  const context = await createAcceptanceContext({',
    '    testInfo,',
    `    sourcePath: ${quote(sourcePath)},`,
    `    scenario: ${quote(scenario.name)}`,
    '  });',
    '',
    '  try {',
    ...steps,
    '  } finally {',
    '    await context.cleanup?.();',
    '  }',
    '});'
  ];
}

function generateStep(sourcePath: string, step: AcceptanceStep): string[] {
  const label = `${step.keyword} ${step.text}`;

  return [
    `// ${sourcePath}:${step.line}`,
    `await test.step(${quote(label)}, async () => {`,
    `  await runAcceptanceStep(context, ${quote(step.text)}, {`,
    `    keyword: ${quote(step.keyword)},`,
    `    text: ${quote(step.text)},`,
    `    sourcePath: ${quote(sourcePath)},`,
    `    line: ${step.line}`,
    '  });',
    '});'
  ];
}

function quote(value: string): string {
  return `'${value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')}'`;
}

function indentLines(lines: string[], spaces: number): string[] {
  const prefix = ' '.repeat(spaces);
  return lines.map((line) => (line === '' ? line : `${prefix}${line}`));
}
