import { readFileSync } from 'node:fs';

const runtimeTemplateUrl = new URL('./templates/playwright-acceptance-runtime.ts.template', import.meta.url);

export interface PlaywrightAcceptanceSpecOptions {
  irImportPath: string;
  runtimeImportPath: string;
  stepsImportPath: string;
}

export function generatePlaywrightAcceptanceSpec(options: PlaywrightAcceptanceSpecOptions): string {
  return [
    '/* Generated by quality-tools acceptance generate. Do not edit. */',
    "import { test } from '@playwright/test';",
    `import { acceptanceSteps, createAcceptanceContext } from ${quote(options.stepsImportPath)};`,
    `import { loadAcceptanceIr, runAcceptanceFeature } from ${quote(options.runtimeImportPath)};`,
    '',
    `const feature = loadAcceptanceIr(${quote(options.irImportPath)});`,
    '',
    'runAcceptanceFeature(test, feature, {',
    '  acceptanceSteps,',
    '  createAcceptanceContext',
    '});',
    ''
  ].join('\n');
}

export function generatePlaywrightAcceptanceRuntime(): string {
  return readFileSync(runtimeTemplateUrl, 'utf8');
}

function quote(value: string): string {
  return `'${value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')}'`;
}
