import { describe, expect, it } from 'vitest';
import { tokenize } from '../../src/organize/naming/tokenize';

describe('tokenize', () => {
  it.each([
    ['reportBlocks', ['report', 'blocks']],
    ['myVariable', ['my', 'variable']],
    ['getValue', ['get', 'value']],
    ['report', ['report']],
    ['getReportBlocksData', ['get', 'report', 'blocks', 'data']],
    ['ReportBlocks', ['report', 'blocks']],
    ['MyVariable', ['my', 'variable']],
    ['Report', ['report']],
    ['GetReportBlocksData', ['get', 'report', 'blocks', 'data']],
    ['HTMLParser', ['html', 'parser']],
    ['XMLHttpRequest', ['xml', 'http', 'request']],
    ['parseJSON', ['parse', 'json']],
    ['buildURL', ['build', 'url']],
    ['HTML', ['html']],
    ['API', ['api']],
    ['AB', ['ab']],
    ['parseHTMLToXML', ['parse', 'html', 'to', 'xml']],
    ['report-blocks', ['report', 'blocks']],
    ['my-variable-name', ['my', 'variable', 'name']],
    ['report_blocks', ['report', 'blocks']],
    ['my_variable_name', ['my', 'variable', 'name']],
    ['report.blocks', ['report', 'blocks']],
    ['my.variable.name', ['my', 'variable', 'name']],
    ['myHTMLParser-v2', ['my', 'html', 'parser', 'v', '2']],
    ['report_blocks.data', ['report', 'blocks', 'data']],
    ['MyReport-DataBlocks_v1', ['my', 'report', 'data', 'blocks', 'v', '1']],
    ['reportBlocks.ts', ['report', 'blocks']],
    ['reportBlocks.tsx', ['report', 'blocks']],
    ['reportBlocks.js', ['report', 'blocks']],
    ['reportBlocks.jsx', ['report', 'blocks']],
    ['reportBlocks.test.ts', ['report', 'blocks']],
    ['reportBlocks.test.tsx', ['report', 'blocks']],
    ['reportBlocks.spec.ts', ['report', 'blocks']],
    ['reportBlocks.spec.tsx', ['report', 'blocks']],
    ['report.blocks.ts', ['report', 'blocks']],
    ['ALLUPPERCASE', ['alluppercase']],
    ['aReport', ['a', 'report']],
    ['v2', ['v', '2']],
    ['myA', ['my', 'a']],
    ['', []],
    ['.ts', []],
    ['.test.ts', []],
    ['---', []],
    ['___', []],
    ['...', []],
    ['report--blocks', ['report', 'blocks']],
    ['report__blocks', ['report', 'blocks']],
    ['index.ts', ['index']],
    ['README.md', ['readme', 'md']],
    ['package.json', ['package', 'json']],
    ['useCustomHookV2.ts', ['use', 'custom', 'hook', 'v', '2']],
    ['myHTMLRenderer.tsx', ['my', 'html', 'renderer']],
    ['JSON_Parser.js', ['json', 'parser']],
    ['node_modules', ['node', 'modules']],
    ['src', ['src']],
    ['APIv3', ['ap', 'iv', '3']],
    ['XMLParser', ['xml', 'parser']],
    ['HTMLElement', ['html', 'element']],
    ['v0release', ['v', '0', 'release']],
    ['v9release', ['v', '9', 'release']],
    ['2fast', ['2', 'fast']],
    ['v2release', ['v', '2', 'release']],
    ['file2Open', ['file', '2', 'open']],
    ['report  blocks', ['report', 'blocks']],
    ['report\tblocks', ['report', 'blocks']],
    ['AZParser', ['az', 'parser']],
    ['z{value', ['z', 'value']]
  ])('tokenizes %s', (input, expected) => {
    expect(tokenize(input)).toEqual(expected);
  });
});
