/* Generated by quality-tools acceptance generate. Do not edit. */
/* eslint-disable playwright/expect-expect */
import fs from 'node:fs';
import type { TestInfo } from '@playwright/test';

export interface AcceptanceIrStep {
  keyword: string;
  text: string;
  line: number;
  parameters: string[];
}

export interface AcceptanceIrExampleRow {
  line: number;
  values: Record<string, string>;
}

export interface AcceptanceIrScenario {
  name: string;
  line: number;
  steps: AcceptanceIrStep[];
  examples: AcceptanceIrExampleRow[];
}

export interface AcceptanceIrDocument {
  schema_version: 1;
  source_path: string;
  feature: { name: string; line: number };
  background?: { line: number; steps: AcceptanceIrStep[] };
  scenarios: AcceptanceIrScenario[];
}

export type AcceptanceContext = { cleanup?: () => unknown | Promise<unknown> };

export interface AcceptanceRuntimeStep {
  keyword: string;
  text: string;
  sourceText: string;
  sourcePath: string;
  line: number;
  parameters: string[];
  example: Record<string, string>;
}

export type AcceptanceStepImplementation = (
  context: AcceptanceContext,
  step: AcceptanceRuntimeStep
) => unknown | Promise<unknown>;

export type AcceptanceStepRegistry = Record<string, AcceptanceStepImplementation>;

export interface AcceptanceBindings {
  acceptanceSteps: unknown;
  createAcceptanceContext: (input: {
    testInfo: TestInfo;
    sourcePath: string;
    scenario: string;
    example: Record<string, string>;
  }) => unknown | Promise<unknown>;
}

type PlaywrightTest = {
  (title: string, callback: (fixtures: object, testInfo: TestInfo) => Promise<void>): void;
  describe(title: string, callback: () => void): void;
  step(title: string, callback: () => Promise<void>): Promise<void>;
};

interface ScenarioExecution {
  name: string;
  scenario: AcceptanceIrScenario;
  example: AcceptanceIrExampleRow;
  steps: AcceptanceRuntimeStep[];
}

export function loadAcceptanceIr(filePath: string): AcceptanceIrDocument {
  return JSON.parse(fs.readFileSync(filePath, 'utf8')) as AcceptanceIrDocument;
}

export function runAcceptanceFeature(
  test: PlaywrightTest,
  feature: AcceptanceIrDocument,
  bindings: AcceptanceBindings
): void {
  test.describe(feature.feature.name, () => {
    expandScenarioExecutions(feature).forEach((execution) => {
      test(execution.name, async ({}, testInfo) => {
        const context = await bindings.createAcceptanceContext({
          testInfo,
          sourcePath: feature.source_path,
          scenario: execution.name,
          example: execution.example.values
        }) as AcceptanceContext;

        try {
          for (const step of execution.steps) {
            await test.step(`${step.keyword} ${step.text}`, async () => {
              await runAcceptanceStep(bindings.acceptanceSteps, context, step);
            });
          }
        } finally {
          await context.cleanup?.();
        }
      });
    });
  });
}

function expandScenarioExecutions(feature: AcceptanceIrDocument): ScenarioExecution[] {
  return feature.scenarios.flatMap((scenario) => {
    const examples = scenario.examples.length > 0
      ? scenario.examples
      : [{ line: scenario.line, values: {} }];

    return examples.map((example) => ({
      name: scenario.examples.length > 0
        ? `${scenario.name} (${formatExampleName(example.values)})`
        : scenario.name,
      scenario,
      example,
      steps: [...(feature.background?.steps ?? []), ...scenario.steps].map((step) => ({
        keyword: step.keyword,
        text: renderStepText(step.text, example.values),
        sourceText: step.text,
        sourcePath: feature.source_path,
        line: step.line,
        parameters: step.parameters,
        example: example.values
      }))
    }));
  });
}

async function runAcceptanceStep(
  registryInput: unknown,
  context: AcceptanceContext,
  step: AcceptanceRuntimeStep
): Promise<void> {
  const implementation = findAcceptanceStepImplementation(registryInput as AcceptanceStepRegistry, step);

  if (!implementation) {
    throw new Error(`Missing acceptance step "${step.keyword} ${step.text}" at ${step.sourcePath}:${step.line}`);
  }

  await implementation(context, step);
}

function findAcceptanceStepImplementation(
  registry: AcceptanceStepRegistry,
  step: AcceptanceRuntimeStep
): AcceptanceStepImplementation | undefined {
  return registry[step.text]
    ?? registry[`${step.keyword} ${step.text}`]
    ?? registry[step.sourceText]
    ?? registry[`${step.keyword} ${step.sourceText}`];
}

function renderStepText(text: string, values: Record<string, string>): string {
  return text.replace(/<([^>]+)>/g, (placeholder, key: string) => values[key] ?? placeholder);
}

function formatExampleName(values: Record<string, string>): string {
  const explicitName = values.case ?? values.name ?? values.title ?? values.example;
  if (explicitName) {
    return explicitName;
  }

  return Object.entries(values)
    .map(([key, value]) => `${key}: ${value}`)
    .join(', ');
}
